inherit_from:
  - .rubocop_airbnb.yml

Rails:
  Enabled: true

AllCops:
  Exclude:
    - 'bin/**'
    - 'config/**/*'
    - 'db/**/*'
    - 'vendor/**/**/*'
    - 'spec/*'

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Layout/FirstHashElementLineBreak:
  Enabled: false

Airbnb/OptArgParameters:
  Enabled: false

Style/ColonMethodCall:
  Enabled: false

Layout/IndentationConsistency:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Metrics/LineLength:
  Max: 150

Rails/HelperInstanceVariable:
  Enabled: false
  
Lint/AssignmentInCondition:
  Enabled: false

Airbnb/DefaultScope:
  Enabled: false

Lint/UselessAssignment:
  Exclude:
    - 'app/uploaders/*'

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Layout/FirstArrayElementLineBreak:
  Enabled: false

Airbnb/RiskyActiverecordInvocation:
  Enabled: false

Layout/MultilineArrayBraceLayout:
  Enabled: false

Airbnb/ContinuationSlash:
  Enabled: false

Style/MultilineTernaryOperator:
  Enabled: false

RSpec/EmptyExampleGroup:
  Enabled: false